// angular/src/app/app.component.ts
import { Component, SimpleChanges } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular';
  items: string[] = [];
  str: string = '';

  ngOnInit() {
    this.items = JSON.parse(localStorage.getItem('todo-list') || '[]');
  }

  addItem() {
    console.log(this.str);
    if (this.str) {
      this.items.push(this.str);
      localStorage.setItem('todo-list', JSON.stringify(this.items));
      this.str = '';
    }
  }
}

<ul>
  <li *ngFor="let item of items">{{ item }}</li>
</ul>
<input [(ngModel)]="str" />
<button (click)="addItem()">Add todo</button>

// svelte/src/App.svelte
<script>
  import { onMount } from 'svelte';

  let items = [];
  let str = '';

  onMount(() => {
    items = JSON.parse(localStorage.getItem('todo-list') || '[]');
  })

  function addItem() {
    if (str) {
      items = [...items, str];
      localStorage.setItem('todo-list', JSON.stringify(items));
      str = ''
    }
  }
</script>

<main>
  <ul>
    {#each items as item}
      <li>{item}</li>
    {/each}
  </ul>
  <input bind:value={str}/>
  <button on:click={addItem}>Add todo</button>
</main>

<style>
</style>
