// react/src/App.js
import { useEffect, useState } from 'react';

function App() {
  const [items, setItems] = useState([]);
  const [str, setStr] = useState('');

  useEffect(() => {
    setItems(JSON.parse(localStorage.getItem('todo-list') || '[]'));
  }, []);

  useEffect(() => {
    if (items.length) {
      localStorage.setItem('todo-list', JSON.stringify(items));
    }
  }, [items]);

  return (
    <>
      <ul>
        {items.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
      <input
        value={str}
        onChange={(e) => {
          setStr(e.target.value);
        }}
      />
      <button
        onClick={() => {
          if (str) {
            setItems((prev) => [...prev, str]);
            setStr('');
          }
        }}
      >
        Add todo
      </button>
    </>
  );
}

export default App;

// solid/src/App.jsx
import { createEffect, createSignal, Index, onMount } from 'solid-js';

function App() {
  const [items, setItems] = createSignal([]);
  const [str, setStr] = createSignal([]);

  onMount(() => {
    setItems(JSON.parse(localStorage.getItem('todo-list') || '[]'));
  });

  // createEffect(() => {
  //   localStorage.setItem('todo-list', JSON.stringify(items()));
  // });

  const addItem = () => {
    if (str()) {
      setItems([...items(), str()]);
      localStorage.setItem('todo-list', JSON.stringify(items()));
      setStr('');
    }
  };

  return (
    <>
      <ul>
        <Index each={items()}>{(item) => <li>{item}</li>}</Index>
      </ul>
      <input
        value={str()}
        onChange={(e) => {
          setStr(e.target.value);
        }}
      />
      <button onClick={addItem}>Add todo</button>
    </>
  );
}

export default App;
